### ISSUE TITLE
It works but I've error messages.

### ISSUE THREAD

**Issue by 01ivier** [iem-projects/patch2svg-plugin#1]
Hi

I've tried patch2svg-plugin both with Puredata 0.45.4 and Pd-extended 0.43.4 on Ubuntu 14.04.
It works fine on both, thank you.
But, I've got those error messages in the console each time I start Pd and Pd-ext:

`-----------
(Tcl) ERREUR NON GÉRÉE : invalid command name "::pd_connect::register_plugin_dispatch_receiver"
    while executing
"::pd_connect::register_plugin_dispatch_receiver ::patch2svg::exportall ::patch2svg::exportall"
    (procedure "::patch2svg::register" line 16)
    invoked from within
"::patch2svg::register"
    ("uplevel" body line 1707)
    invoked from within
"uplevel #0 $tclcode"IMPOSSIBLE DE CHARGER /usr/lib/pd/extra/patch2svg-plugin.tcl
-----------`

**Comment by ml4rrieu** [comment]
same behavior (works fine but with this error message) on my computer :  pd extended 0.43.4 on win7.
