### ISSUE TITLE
plugin doesn't seem to work well (macOS)

### ISSUE THREAD

**Issue by porres** [iem-projects/patch2svg-plugin#2]
Hi, I'm on Mojave, using Pd.0.49-1, as a suggestion in the Pd list, I'm trying this plugin to export a patch as an image, but it doesn't look the same as the original patch at all. I get even more differences than using  "print" to export it as an image. Here's a screenshot, with how the patch actually looks.

<img width="570" alt="screen" src="https://user-images.githubusercontent.com/5360142/52249695-925c9280-28db-11e9-8af1-a5502b80a187.png">

And now the image I get from the plugin

<img width="585" alt="svg" src="https://user-images.githubusercontent.com/5360142/52249708-a43e3580-28db-11e9-9595-746636479c66.png">

The font does not look the same, for sure, so I guess the wrong font is one of the crucial issues.

**Comment by umlaeute** [comment]
for now, i guess you could open the SVG with some SVG editor and set the font to whatever Pd is using.

and please change the title to something meaningful.

**Comment by umlaeute** [comment]
also, please post the SVG you got, and the (name of) the font your Pd is using.

**Comment by umlaeute** [comment]
i think i found the problem:
- Pd ships a local font `DejaVuSansMono.ttf` somewhere in the Resources folder
- the patch2svg plugin references this font in the generated SVG
- when opening the SVG with your favourite image viewer, it doesn't find the font (as it is installed in Pd's private resources folder, and not available system-wide)
- instead it falls back to some default font

the solution is to install the `DejaVuSansMono.ttf`in some system fonts folder (check your OS manual on how to do that), before viewing it.

**Comment by porres** [comment]
thanks
