### ISSUE TITLE
space to the right of object names inside objects missing, or font size to big?

### ISSUE THREAD

**Issue by musger** [iem-projects/patch2svg-plugin#3]
I have noticed that there is less space to the right of object names or argumentes and the object box border than to the left. For long object names or arguments this will cause text to flow over the object border. This is with Pd 0.50.0-1 on Debian 

![long svg](https://user-images.githubusercontent.com/33548774/66389300-9c2d1d00-e9b7-11e9-8958-87264983294b.png)

**Comment by umlaeute** [comment]
is that on the same machine where you did the export?

if so, it might be related to fonts (the resulting SVG just references the font for displaying text, it doesn't embed it)

**Comment by musger** [comment]
* umläute <notifications@github.com> [2019-10-08 14:07]:
> is that on the same machine where you did the export?
Yes, actually the behavior is the same on another debian machine but
with similar if not identical configuration and packages installed and
also for a newly created user.
 
> if so, it might be related to fonts (the resulting SVG just references the font for displaying text, it doesn't embed it)
I am also having the issue with the gui font being larger than 12, see
https://lists.puredata.info/pipermail/pd-list/2018-04/122278.html
and wonder if the two are related.

Can you reproduce this by any chance on your box?

thänks,
P

**Comment by umlaeute** [comment]
i got something completely else, depending on the SVG viewer.

At startup, Pd prints:
> Detected font: DejaVu Sans Mono
> Using font: Courier 10 Pitch bold

The resulting SVG uses `Courier 10 Pitch` as the font.

With geeqie and the GIMP, this SVG uses replacement characters.

Geeqie
![geeqie_courier](https://user-images.githubusercontent.com/214034/66418988-8ba29400-ea03-11e9-8a65-92d3bb7997db.png)

the GIMP
![gimp_courier](https://user-images.githubusercontent.com/214034/66418999-90674800-ea03-11e9-8be5-52fc55f66030.png)

ImageMagick's `convert`:
![magick_courier](https://user-images.githubusercontent.com/214034/66419017-952bfc00-ea03-11e9-98ef-a0997bfae513.png)

If I manually change the font-family in the SVG from `Courier 10 Pitch` to `DejaVu Sans Mono`, geeqie renders the image nicely and as expected, but both the GIMP and ImageMagick have trouble:

Geeqie:
![geeqie_dejavu](https://user-images.githubusercontent.com/214034/66419125-cb697b80-ea03-11e9-857c-04e9d253a107.png)
the GIMP:
![gimp_dejavu](https://user-images.githubusercontent.com/214034/66419137-cefd0280-ea03-11e9-900e-e17b740f9131.png)
ImageMagick's `convert`:
![magick_dejavu](https://user-images.githubusercontent.com/214034/66419143-d15f5c80-ea03-11e9-895d-8849f11b97c3.png)

i'm not sure what's fishy here, but i don't see anything wrong on the platch2svg plugin side.

**Comment by musger** [comment]
So I just found out that this issue does not persist when I set Pd's font size to 10 instead of 12. I don't know what your font size was set to when you did tests, would you mind running a quick test with both values eventually? Thanks!

**Comment by umlaeute** [comment]
i can confirm that with `fontsize:12` exceeds the bounding-box, wherease `fontsize:10` does not (using `DejaVu Sans Mono`).

comparing a screenshot of the patch with the SVG converted to PNG (with `convert`) it seems that the *spacing* between the letters (*kerning*?)  is the issue.

**Comment by musger** [comment]
* umläute ***@***.***> [2023-08-07 11:33]:
> i can confirm that with `fontsize:12` exceeds the bounding-box, wherease `fontsize:10` does not (using `DejaVu Sans Mono`).
> 
> comparing a screenshot of the patch with the SVG converted to PNG (with `convert`) it seems that the *spacing* between the letters (*kerning*?)  is the issue.
Thanks! I usually use
	inkscape --export-type=pdf B07.sampler.pd.svg
for the same task. I can not test this on other OSes, did you have the
chance to take a look there as well?

**Comment by umlaeute** [comment]
could you check whether the current master fixes the problem?

**Comment by musger** [comment]
It does, thank you so much! Amazing!

* umläute ***@***.***> [2023-08-07 15:24]:
